name: Playwright Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3        
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Specify the pnpm version here

  test:
    needs: install
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Specify the pnpm version here
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - name: Start server
        run: pnpm start &
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
